model_dir: content/data

data:
  train_features_file: data/demo_train_new_Tatoeba.be-ru.be
  train_labels_file: data/demo_train_lang_Tatoeba.be-ru.ru
  eval_features_file: data/demo_valnew_Tatoeba.be-ru.be
  eval_labels_file: data/demo_vallang_Tatoeba.be-ru.ru
  source_vocabulary: data/be-vocab.txt
  target_vocabulary: data/ru-vocab.txt

train:
  save_checkpoints_steps: 1000

  eval:
    save_eval_predictions: true
    steps: 100  # Every 1 hour
    scorers: bleu
infer:
    batch_size: 32







